# Generated by Django 5.0.4 on 2024-04-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journal_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='emotion',
        ),
    ]
